### ISSUE TITLE
ETL/Taxi_ETL.ipynb result have some problem

### ISSUE THREAD

**Issue by mao-ouyang** [rapidsai/spark-examples#58]
1. The year, month, and day series passed by this function uses the reference instead of passing the value, thus causing the original data to be modified.
![image](https://user-images.githubusercontent.com/46299753/66569283-c4767080-eb9d-11e9-86af-a52f4b06d430.png)
Improve proposals：
![image](https://user-images.githubusercontent.com/46299753/66570829-ef15f880-eba0-11e9-92da-5807b2747f75.png)
2. When exporting data using pandas, the index column should be removed.
![image](https://user-images.githubusercontent.com/46299753/66570666-a3fbe580-eba0-11e9-860a-4873546e8980.png)
Improve proposals：
![image](https://user-images.githubusercontent.com/46299753/66570703-b2e29800-eba0-11e9-90c0-68fa296927ee.png)

**Comment by krajendrannv** [comment]
Thanks for your feedback. Please feel free to submit a pull request.

**Comment by chuanlihao** [comment]
Hi @mao-ouyang , thanks for pointing out these issues.

You are correct. I have verified these issues on my local server. There is one more issue that "train_part_path_csv" should be updated to "test_part_path_csv" when saving csv test data.

It would be great if you could submit a pull request to fix these issues. If you don't have time to do it, please let me know then I will fix the issues. Thanks a lot.

**Comment by anfeng** [comment]
Assuming the issue was resolved per latest suggestion. Feel free to reopen if you still have the problem
