### ISSUE TITLE
Run on multiple GPU

### ISSUE THREAD

**Issue by BlueFelix** [rapidsai/spark-examples#64]
I use 2 executors and run the xgboost demo. I tried to change spark.sql.files.maxPartitionBytes and maxRowsPerChunk but it always has 1 partition and run on single executor and single GPU. How to use multiple GPU?

**Comment by BlueFelix** [comment]
It's controled by  numWorkers of xgboost's params

**Comment by anfeng** [comment]
How many data partitions do you have? You need to specify 2 executors and 2 workers.

**Comment by sameerz** [comment]
Was this issue resolved (numWorkers = number of GPUs)?
